ALTER TABLE "Invoice"
  ADD COLUMN "discountType" TEXT NOT NULL DEFAULT 'none',
  ADD COLUMN "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "LineItem"
  ADD COLUMN "discountType" TEXT NOT NULL DEFAULT 'none',
  ADD COLUMN "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
